version: "3.8"
services:
  php-apache:
    build: php-apache
    container_name: php-apache
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: rianzaputra
        MYSQL_DATABASE: db_testing
        MYSQL_USER: rian
        MYSQL_PASSWORD: zaputra
    ports:
        - "3306:3306"